import { Exercise } from '../types';

const adv94: Exercise = {
  id: 'adv-94',
  unitId: 'unit16-advanced',
  title: '94: FSOP (File Stream Oriented Programming)',
  desc: '<b>Goal:</b> Execute the most advanced FILE exploitation technique \u2014 File Stream Oriented Programming. FSOP chains heap corruption with the FILE structure linked list to achieve arbitrary code execution through <code>__overflow</code>.<br><br><b>How FSOP works:</b><br>1. glibc maintains a linked list of all FILE streams via <code>_IO_list_all</code> (a global pointer).<br>2. On <code>abort()</code> or <code>exit()</code>, glibc calls <code>_IO_flush_all_lockp()</code>, which walks <code>_IO_list_all</code> and calls <code>__overflow</code> on each FILE whose write pointer (<code>_IO_write_ptr</code>) exceeds its write end (<code>_IO_write_end</code>).<br>3. If you corrupt the unsorted bin (via heap overflow/UAF), a failed <code>malloc</code> triggers <code>malloc_printerr</code> -> <code>abort()</code> -> <code>_IO_flush_all_lockp()</code>.<br>4. By placing a crafted fake FILE structure at a known address and linking it via the unsorted bin attack (overwriting <code>_IO_list_all</code>), you control the vtable pointer. When <code>__overflow</code> is called, it jumps to your address.<br><br><b>Key constraints for triggering __overflow:</b><br><code>fp->_IO_write_ptr > fp->_IO_write_end</code> (forces the flush path)<br><code>fp->_mode <= 0</code> (avoids wide-char path)<br><code>fp->__vtable->__overflow = win</code><br><br>Overflow the buffer to overwrite the return address with <code>win()</code>, modeling the FSOP control-flow hijack.',
  source: {
    c: [
      { text: '// FSOP: File Stream Oriented Programming', cls: 'cmt' },
      { text: '// _IO_list_all -> stdout -> stderr -> ...', cls: 'cmt' },
      { text: '', cls: '' },
      { text: '// On abort()/exit():', cls: 'cmt' },
      { text: '//   _IO_flush_all_lockp() walks _IO_list_all', cls: 'cmt' },
      { text: '//   For each FILE: if _IO_write_ptr > _IO_write_end', cls: 'cmt' },
      { text: '//     -> call vtable->__overflow(fp, EOF)', cls: 'cmt' },
      { text: '', cls: '' },
      { text: '// Attack chain:', cls: 'cmt' },
      { text: '// 1. Corrupt unsorted bin -> overwrite _IO_list_all', cls: 'cmt' },
      { text: '// 2. _IO_list_all now points to crafted fake FILE', cls: 'cmt' },
      { text: '// 3. Fake FILE has: write_ptr > write_end', cls: 'cmt' },
      { text: '// 4. Fake FILE->vtable->__overflow = win()', cls: 'cmt' },
      { text: '// 5. Trigger abort() via corrupted heap -> BOOM', cls: 'cmt' },
      { text: '', cls: '' },
      { text: 'void win() { printf("FLAG\\n"); }', cls: '' },
      { text: '', cls: '' },
      { text: 'void vuln() {', cls: '', fn: true },
      { text: '    char buf[16];', cls: 'highlight' },
      { text: '    // heap setup: unsorted bin attack', cls: 'cmt' },
      { text: '    gets(buf);', cls: 'highlight vuln' },
      { text: '    // Triggers: malloc_printerr -> abort()', cls: 'cmt' },
      { text: '    // -> _IO_flush_all_lockp()', cls: 'cmt' },
      { text: '    // -> fake_file->vtable->__overflow()', cls: 'cmt' },
      { text: '    // -> win()!', cls: 'cmt' },
      { text: '}', cls: '' },
      { text: '', cls: '' },
      { text: '// Fake FILE structure layout:', cls: 'cmt' },
      { text: '// _flags      = 0x00000000', cls: 'cmt' },
      { text: '// _IO_write_ptr = 0x1  (must be > write_end)', cls: 'cmt' },
      { text: '// _IO_write_end = 0x0', cls: 'cmt' },
      { text: '// _mode       = 0x0  (must be <= 0)', cls: 'cmt' },
      { text: '// __vtable    = &fake_vtable', cls: 'cmt' },
      { text: '// fake_vtable.__overflow = win', cls: 'cmt' },
    ],
  },
  mode: 'input-hex',
  vizMode: 'stack',
  bufSize: 16,
  showSymbols: true,
  showBuilder: true,
  check(sim, _heap, symbols) {
    return sim.getRetAddr() === symbols.win;
  },
  winTitle: 'FLAG{fsop_master}',
  winMsg: 'You mastered File Stream Oriented Programming \u2014 the apex of glibc heap exploitation. By chaining an unsorted bin attack to overwrite _IO_list_all with a crafted fake FILE structure, you triggered __overflow through the abort() -> _IO_flush_all_lockp() path. This technique, introduced in the "House of Orange" paper, remains relevant in modern CTFs and was the basis for several real-world glibc exploitation chains. In glibc 2.24+, the _IO_str_jumps bypass extends this technique past IO_validate_vtable.',
  realWorld: 'CVE-2017-1000366 (Stack Clash + glibc): Combined stack-heap collision with FSOP-style FILE structure corruption to achieve local privilege escalation on Linux systems.',
};

export default adv94;
