import { Exercise } from '../types';

export const mips78: Exercise = {
  id: 'mips-78',
  unitId: 'unit14-mips',
  title: 'MIPS ROP',
  desc: 'Chain MIPS ROP gadgets to write a magic value and call <code>win()</code>. On MIPS, gadgets end with <code>jr $ra</code> instead of <code>ret</code>. Because MIPS uses a <b>split instruction/data cache</b>, injecting shellcode is unreliable — the CPU may execute stale cache instead of your injected code. This makes <b>ROP the dominant exploitation technique</b> on MIPS. Each gadget loads the next <code>$ra</code> from the stack, then jumps to it.',
  source: {
    c: [
      { text: '/* MIPS ROP — JR $RA Gadget Chaining */', cls: 'cmt' },
      { text: '', cls: '' },
      { text: '/* MIPS cache coherency problem: */', cls: 'cmt' },
      { text: '/*   I-cache and D-cache are separate */', cls: 'cmt' },
      { text: '/*   Writing shellcode to data memory */', cls: 'cmt' },
      { text: '/*   does NOT update the I-cache! */', cls: 'cmt' },
      { text: '/*   So shellcode injection often fails */', cls: 'cmt' },
      { text: '/*   → ROP is the primary technique */', cls: 'cmt' },
      { text: '', cls: '' },
      { text: '/* Gadgets (all end with jr $ra): */', cls: 'cmt' },
      { text: '/* 0x00400300: lw $a0, 0($sp); */', cls: 'cmt' },
      { text: '/*             lw $ra, 4($sp); jr $ra */', cls: 'cmt' },
      { text: '/* 0x00400310: lw $a1, 0($sp); */', cls: 'cmt' },
      { text: '/*             lw $ra, 4($sp); jr $ra */', cls: 'cmt' },
      { text: '/* 0x00400320: sw $a0, 0($a1); */', cls: 'cmt' },
      { text: '/*             lw $ra, 4($sp); jr $ra */', cls: 'cmt' },
      { text: '', cls: '' },
      { text: 'int flag = 0; /* at 0x00410040 */', cls: 'highlight' },
      { text: '', cls: '' },
      { text: 'void win() {', cls: '' },
      { text: '    if (flag == 0xdeadbeef)', cls: '' },
      { text: '        printf("FLAG{mips_rop}\\n");', cls: '' },
      { text: '}', cls: '' },
      { text: '', cls: '' },
      { text: 'void vuln() {', cls: '', fn: true },
      { text: '    char buf[16];', cls: '' },
      { text: '    gets(buf);', cls: 'highlight vuln' },
      { text: '}', cls: '' },
    ],
  },
  mode: 'input-hex',
  vizMode: 'stack',
  bufSize: 16,
  showSymbols: true,
  showBuilder: true,
  showGadgetTable: true,
  nx: true,
  rop: true,
  gadgets: {
    0x00400300: 'lw $a0, 0($sp); lw $ra, 4($sp); jr $ra',
    0x00400310: 'lw $a1, 0($sp); lw $ra, 4($sp); jr $ra',
    0x00400320: 'sw $a0, 0($a1); lw $ra, 4($sp); jr $ra',
  },
  flagAddr: 0x00410040,
  magicValue: 0xdeadbeef,
  check(_sim, _heap, _symbols, flags) {
    return flags.ropWin === true;
  },
  winTitle: 'FLAG{mips_rop}',
  winMsg: 'You chained MIPS ROP gadgets using JR $RA! On MIPS routers and embedded devices, ROP is the primary exploitation technique because the split I-cache/D-cache makes shellcode injection unreliable. Many real-world MIPS exploits (home routers, IoT devices) use this exact approach.',
};
