import { Exercise } from '../types';

export const win43: Exercise = {
  id: 'win-43',
  unitId: 'unit9-win-heap',
  title: 'LFH Basics',
  desc: '<b>Goal:</b> The Low Fragmentation Heap (LFH) is Windows\' equivalent of glibc\'s tcache/fastbins. When a size class gets 17+ allocations, the LFH activates for that size. LFH uses <b>randomized allocation order</b> within buckets — unlike glibc which is LIFO. This makes heap exploitation significantly harder on Windows.',
  source: {
    c: [
      { text: '// Windows Low Fragmentation Heap (LFH)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Comparison with glibc:', cls: 'comment' },
      { text: '// glibc tcache  →  LFH bucket', cls: 'comment' },
      { text: '// glibc fastbin →  LFH (similar size range)', cls: 'comment' },
      { text: '// glibc bins    →  Backend allocator', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// LFH activation:', cls: 'comment' },
      { text: '// After 17+ allocs of same size class', cls: 'comment' },
      { text: '// LFH "activates" for that bucket', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Size classes (buckets):', cls: 'comment' },
      { text: '// 1-8 bytes     → bucket 1  (granularity 8)', cls: 'comment' },
      { text: '// 9-16 bytes    → bucket 2', cls: 'comment' },
      { text: '// 17-24 bytes   → bucket 3', cls: 'comment' },
      { text: '// ...up to 16KB → bucket 128', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Key difference from glibc:', cls: 'comment' },
      { text: '// LFH uses RANDOMIZED allocation within buckets', cls: 'comment' },
      { text: '// No deterministic LIFO ordering!', cls: 'comment' },
      { text: '// Makes use-after-free exploitation harder', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 16', comment: 'Request 16 bytes from HeapAlloc' },
    { addr: 0x00401005, bytes: [0xbb], mnemonic: 'mov', operands: 'ebx, 0x00380000', comment: 'Heap handle (process default heap)' },
    { addr: 0x0040100a, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 8', comment: 'Bucket granularity = 8 bytes' },
    { addr: 0x0040100f, bytes: [0xba], mnemonic: 'mov', operands: 'edx, 2', comment: 'Bucket 2 (size 9-16)' },
    { addr: 0x00401014, bytes: [0xbe], mnemonic: 'mov', operands: 'esi, 17', comment: 'LFH activation threshold' },
    { addr: 0x00401019, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'LFH basics understood!' },
  ],
  check: () => true,
  winTitle: 'LFH Basics!',
  winMsg: 'You understand the Windows Low Fragmentation Heap architecture.',
};
