import { Exercise } from '../types';

export const win44: Exercise = {
  id: 'win-44',
  unitId: 'unit9-win-heap',
  title: 'LFH Overflow',
  desc: '<b>Goal:</b> Despite randomization, LFH heap overflows can still corrupt adjacent chunks. The key challenge is that you don\'t know <i>which</i> chunk is adjacent. Technique: spray the heap (allocate many same-size chunks) to increase probability of controlling what\'s next to your target. Then overflow into the adjacent chunk\'s data.',
  source: {
    c: [
      { text: '// LFH Heap Overflow', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Challenge: LFH randomizes allocation order', cls: 'comment' },
      { text: '// You don\'t know what\'s adjacent!', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Solution: Heap Spray', cls: 'comment' },
      { text: '// 1. Allocate many chunks of target size', cls: 'comment' },
      { text: '// 2. Free every other one', cls: 'comment' },
      { text: '// 3. Allocate the victim object', cls: 'comment' },
      { text: '// 4. Overflow — likely hits a sprayed chunk', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// LFH chunk metadata:', cls: 'comment' },
      { text: '// [8-byte header] [user data]', cls: 'comment' },
      { text: '// Header is ENCODED (XORed with random key)', cls: 'comment' },
      { text: '// Can\'t just overwrite metadata like glibc!', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Strategy: overflow into USER DATA of adjacent', cls: 'comment' },
      { text: '// chunk (function pointer, vtable ptr, etc.)', cls: 'comment' },
      { text: '// Don\'t touch the encoded header', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 100', comment: 'Spray: allocate 100 chunks of size 32' },
    { addr: 0x00401005, bytes: [0xbb], mnemonic: 'mov', operands: 'ebx, 32', comment: 'Each chunk is 32 bytes' },
    { addr: 0x0040100a, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 50', comment: 'Free every other: 50 holes' },
    { addr: 0x0040100f, bytes: [0xba], mnemonic: 'mov', operands: 'edx, 0x00500000', comment: 'Victim object allocated in a hole' },
    { addr: 0x00401014, bytes: [0xbe], mnemonic: 'mov', operands: 'esi, 0x41414141', comment: 'Overflow 36 bytes → into adjacent chunk data' },
    { addr: 0x00401019, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'Adjacent chunk\'s function ptr corrupted!' },
  ],
  check: () => true,
  winTitle: 'LFH Overflow!',
  winMsg: 'You understand heap spraying and LFH overflow techniques.',
};
