import { Exercise } from '../types';

export const win45: Exercise = {
  id: 'win-45',
  unitId: 'unit9-win-heap',
  title: 'Segment Heap',
  desc: '<b>Goal:</b> Windows 10+ introduces the <b>Segment Heap</b> — a completely new allocator replacing the NT heap for system processes and apps. It has Variable Size (VS), Low Fragmentation (LFH), and Large Block segments. Metadata is encoded, free lists are randomized, and guard pages are inserted. This is Microsoft\'s answer to heap exploitation.',
  source: {
    c: [
      { text: '// Segment Heap (Windows 10+)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Architecture:', cls: 'comment' },
      { text: '// SegmentHeap', cls: 'comment' },
      { text: '//   ├── VS Segment    (variable size, < 128KB)', cls: 'comment' },
      { text: '//   ├── LFH Segment   (fixed size buckets)', cls: 'comment' },
      { text: '//   └── Large Blocks   (> 128KB, VirtualAlloc)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Enabled for:', cls: 'comment' },
      { text: '// - UWP apps (always)', cls: 'comment' },
      { text: '// - System processes (svchost, etc.)', cls: 'comment' },
      { text: '// - Opted-in Win32 apps', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Security features:', cls: 'comment' },
      { text: '// 1. Encoded metadata (XOR with random key)', cls: 'comment' },
      { text: '// 2. Guard pages between segments', cls: 'comment' },
      { text: '// 3. Randomized free list ordering', cls: 'comment' },
      { text: '// 4. Different from NT heap → breaks old exploits', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Key: NT heap exploits don\'t work here', cls: 'comment' },
      { text: '// Need segment-heap-specific techniques', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 0xABCD1234', comment: 'Segment Heap handle (different from NT heap)' },
    { addr: 0x00401005, bytes: [0xbb], mnemonic: 'mov', operands: 'ebx, 0x100', comment: 'VS segment: variable size allocation (256 bytes)' },
    { addr: 0x0040100a, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 0x10', comment: 'LFH segment: fixed bucket (16 bytes)' },
    { addr: 0x0040100f, bytes: [0xba], mnemonic: 'mov', operands: 'edx, 0x20000', comment: 'Large block: > 128KB → VirtualAlloc directly' },
    { addr: 0x00401014, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'Segment Heap architecture understood!' },
  ],
  check: () => true,
  winTitle: 'Segment Heap!',
  winMsg: 'You understand the Windows 10+ Segment Heap architecture.',
};
