import { Exercise } from '../types';

export const win45: Exercise = {
  id: 'win-45',
  unitId: 'unit9-win-heap',
  title: '45: Double Free',
  desc: 'Windows Segment Heap has protections against double-free, but older NT heap doesn\'t always catch it. This exercise simulates a double-free: free chunk A, free chunk B, free chunk A again. Now <code>malloc</code> returns A twice — write <code>win()</code> into the function pointer.',
  source: {
    c: [
      { text: '#include <stdlib.h>', cls: '' },
      { text: '#include <windows.h>', cls: '' },
      { text: '', cls: '' },
      { text: '// Double Free on Windows', cls: 'comment' },
      { text: '// NT heap: less validation than Segment Heap', cls: 'comment' },
      { text: '', cls: '' },
      { text: 'struct Obj {', cls: '' },
      { text: '    void (*action)();', cls: 'highlight' },
      { text: '    char data[12];', cls: '' },
      { text: '};', cls: '' },
      { text: '', cls: '' },
      { text: 'void win() { system("cmd"); }', cls: '' },
      { text: '', cls: '' },
      { text: 'int main() {', cls: '' },
      { text: '    Obj *a = HeapAlloc(h, 0, 16);', cls: '' },
      { text: '    Obj *b = HeapAlloc(h, 0, 16);', cls: '' },
      { text: '    a->action = normal;', cls: '' },
      { text: '    HeapFree(h, 0, a);', cls: 'highlight vuln' },
      { text: '    HeapFree(h, 0, b);', cls: 'highlight' },
      { text: '    HeapFree(h, 0, a);', cls: 'highlight vuln' },
      { text: '    // a is in free list twice!', cls: 'cmt' },
      { text: '    Obj *c = HeapAlloc(h, 0, 16);', cls: 'highlight' },
      { text: '    read(0, c, 16);', cls: 'highlight vuln' },
      { text: '    a->action();', cls: 'highlight vuln' },
      { text: '}', cls: '' },
    ],
  },
  mode: 'heap-double-free',
  vizMode: 'heap',
  heapSize: 256,
  winVersion: 'win7',
  showSymbols: true,
  showCalc: true,
  check(_, heap, symbols) {
    return heap?.funcPtrs?.action?.current === symbols.win;
  },
  winTitle: 'Double Free!',
  winMsg: 'Double-free corrupts the free list, letting you get the same chunk allocated twice for a write-what-where primitive.',
};
