import { Exercise } from '../types';

export const win46: Exercise = {
  id: 'win-46',
  unitId: 'unit9-win-heap',
  title: 'WinAPI Exploit',
  desc: '<b>Goal:</b> Windows heap functions differ from glibc: <code>HeapCreate</code> creates private heaps, <code>HeapAlloc/HeapFree</code> manage allocations. Private heaps with <code>HEAP_NO_SERIALIZE</code> skip locking — useful for exploits. Custom heaps may lack mitigations present in the process heap.',
  source: {
    c: [
      { text: '// WinAPI Heap Functions', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// vs. glibc:', cls: 'comment' },
      { text: '// malloc()        → HeapAlloc(hHeap, 0, size)', cls: 'comment' },
      { text: '// free()          → HeapFree(hHeap, 0, ptr)', cls: 'comment' },
      { text: '// (no equivalent) → HeapCreate(flags, init, max)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Private heap creation:', cls: 'comment' },
      { text: '// HANDLE h = HeapCreate(', cls: 'comment' },
      { text: '//   HEAP_NO_SERIALIZE,  // no locking!', cls: 'comment' },
      { text: '//   0x1000,             // initial size', cls: 'comment' },
      { text: '//   0                   // no max (growable)', cls: 'comment' },
      { text: '// );', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Exploit implications:', cls: 'comment' },
      { text: '// 1. Custom heaps may skip LFH activation', cls: 'comment' },
      { text: '// 2. HEAP_NO_SERIALIZE = no thread safety', cls: 'comment' },
      { text: '//    → race conditions possible', cls: 'comment' },
      { text: '// 3. HeapReAlloc can move data → dangling ptr', cls: 'comment' },
      { text: '// 4. HeapSize reveals allocation size (info leak)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Key pattern: look for custom HeapCreate', cls: 'comment' },
      { text: '// with HEAP_NO_SERIALIZE or small max size', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0x6a, 0x01], mnemonic: 'push', operands: '1', comment: 'HEAP_NO_SERIALIZE flag (0x1)' },
    { addr: 0x00401002, bytes: [0x68], mnemonic: 'push', operands: '0x1000', comment: 'Initial heap size: 4KB' },
    { addr: 0x00401007, bytes: [0x6a, 0x00], mnemonic: 'push', operands: '0', comment: 'Max size: 0 (growable)' },
    { addr: 0x00401009, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 0x00680000', comment: 'HeapCreate returns handle' },
    { addr: 0x0040100e, bytes: [0x50], mnemonic: 'push', operands: 'eax', comment: 'Push heap handle for HeapAlloc' },
    { addr: 0x0040100f, bytes: [0x6a, 0x00], mnemonic: 'push', operands: '0', comment: 'Flags: 0 (no special flags)' },
    { addr: 0x00401011, bytes: [0x6a, 0x20], mnemonic: 'push', operands: '32', comment: 'Size: 32 bytes' },
    { addr: 0x00401013, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 0x00681000', comment: 'HeapAlloc returns ptr' },
    { addr: 0x00401018, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'Private heap allocated!' },
  ],
  check: () => true,
  winTitle: 'WinAPI Heap!',
  winMsg: 'You understand Windows heap APIs and custom heap exploitation patterns.',
};
