import { Exercise } from '../types';

export const arm70: Exercise = {
  id: 'arm-70',
  unitId: 'unit13-arm',
  title: 'ARM ROP',
  desc: 'ARM ROP (Return-Oriented Programming) works like x86 ROP, but gadgets end with <b>BX LR</b> or <b>POP {pc}</b> instead of RET. Each gadget pops values from the stack into registers, then returns control to the next gadget address on the stack. Chain the gadgets to write <b>0xdeadbeef</b> to the flag address, then jump to <b>win()</b>. Click gadgets in the table to add them to your payload.',
  source: {
    c: [
      { text: '#include <stdio.h>', cls: '' },
      { text: '', cls: '' },
      { text: '// NX enabled — no shellcode on ARM either', cls: 'cmt' },
      { text: '// ARM gadgets end with POP {pc} or BX LR', cls: 'cmt' },
      { text: '// Found these gadgets:', cls: 'cmt' },
      { text: '// 0x00010300: pop {r0, pc}', cls: 'cmt' },
      { text: '// 0x00010304: pop {r1, pc}', cls: 'cmt' },
      { text: '// 0x00010308: str r0, [r1]; pop {pc}', cls: 'cmt' },
      { text: '', cls: '' },
      { text: 'int flag_check = 0; // at 0x00020040', cls: 'highlight' },
      { text: '', cls: '' },
      { text: 'void win() {', cls: '' },
      { text: '    if (flag_check == 0xdeadbeef)', cls: '' },
      { text: '        printf("FLAG{arm_rop_chain}\\n");', cls: '' },
      { text: '}', cls: '' },
      { text: '', cls: '' },
      { text: 'void vuln() {', cls: '', fn: true },
      { text: '    char buf[16];', cls: '' },
      { text: '    gets(buf);', cls: 'highlight vuln' },
      { text: '}', cls: '' },
      { text: '', cls: '' },
      { text: 'int main() {', cls: '' },
      { text: '    vuln();', cls: '' },
      { text: '    return 0;', cls: '' },
      { text: '}', cls: '' },
    ],
  },
  mode: 'input-hex',
  vizMode: 'stack',
  asmArch: 'arm',
  bufSize: 16,
  showSymbols: true,
  showBuilder: true,
  showGadgetTable: true,
  nx: true,
  rop: true,
  gadgets: {
    0x00010300: 'pop {r0, pc}',
    0x00010304: 'pop {r1, pc}',
    0x00010308: 'str r0, [r1]; pop {pc}',
  },
  flagAddr: 0x00020040,
  magicValue: 0xdeadbeef,
  check(_sim, _heap, _symbols, flags) {
    return flags.ropWin === true;
  },
  winTitle: 'FLAG{arm_rop_chain}',
  winMsg: 'You chained ARM ROP gadgets together! On ARM, gadgets use POP {pc} or BX LR instead of x86\'s RET, but the principle is identical: each gadget performs a small operation, then pops the next gadget address off the stack. This is the primary technique for exploiting ARM devices with NX enabled.',
  realWorld: 'CVE-2020-0069: MediaTek-SU exploit used ROP chains on ARM to bypass kernel protections on millions of Android devices, enabling root access from any app.',
};
