import { Exercise } from '../types';

const ex01StackFrame: Exercise = {
  id: 'stack-01',
  unitId: 'unit1-stack',
  title: '01: The Stack Frame',
  desc: 'Watch how a function call sets up memory. Click <strong>Step</strong> to see each piece get placed on the stack — the computer saves where to go back to (return address), saves a bookmark to the previous frame, then makes room for local variables.',
  source: {
    c: [
      { text: '#include <stdio.h>', cls: '' },
      { text: '', cls: '' },
      { text: 'void vuln() {', cls: '', fn: true },
      { text: '    char buf[16];', cls: 'highlight' },
      { text: '    // memory layout on the stack:', cls: 'cmt' },
      { text: '    // [buf 16 bytes] [saved bookmark] [go-back address]', cls: 'cmt' },
      { text: '}', cls: '' },
      { text: '', cls: '' },
      { text: 'int main() {', cls: '' },
      { text: '    vuln();', cls: 'highlight' },
      { text: '    return 0;', cls: '' },
      { text: '}', cls: '' },
    ],
    asm: [
      { text: '; main:', cls: 'cmt' },
      { text: 'main:', cls: '', fn: true },
      { text: '    push ebp', cls: '' },
      { text: '    mov  ebp, esp', cls: '' },
      { text: '    call vuln', cls: 'highlight' },
      { text: '    ; return address pushed here →', cls: 'cmt' },
      { text: '    xor  eax, eax', cls: '' },
      { text: '    pop  ebp', cls: '' },
      { text: '    ret', cls: '' },
      { text: '', cls: '' },
      { text: '; vuln:', cls: 'cmt' },
      { text: 'vuln:', cls: '', fn: true },
      { text: '    push ebp', cls: 'highlight' },
      { text: '    mov  ebp, esp', cls: '' },
      { text: '    sub  esp, 16', cls: 'highlight' },
      { text: '    ; buf is at [ebp-16]', cls: 'cmt' },
      { text: '    leave', cls: '' },
      { text: '    ret', cls: '' },
    ],
  },
  mode: 'step',
  vizMode: 'stack',
  bufSize: 16,
  showSymbols: false,
  showBuilder: false,
  aslr: false,
  steps: [
    { region: 'none', log: ['info', 'main() is about to call vuln()...'] },
    { region: 'ret', log: ['action', 'The computer saves the go-back address so it knows where to return after vuln() finishes'] },
    { region: 'ebp', log: ['action', 'Save a bookmark to the previous frame (saved EBP) — used to clean up later'] },
    { region: 'buffer', log: ['action', 'Make room for buf[] — 16 bytes of space for our input'] },
    { region: 'all', log: ['info', 'Done! The stack now has: our buffer (green), the saved bookmark (blue), and the go-back address (orange). The go-back address is the key — it controls where the program goes next.'] },
  ],
  check() { return false; },  // eslint-disable-line @typescript-eslint/no-unused-vars
  winTitle: 'Stack Frame Complete',
  winMsg: 'You have observed how a stack frame is constructed.',
};

export default ex01StackFrame;
