import { Exercise } from '../types';

export const win41: Exercise = {
  id: 'win-41',
  unitId: 'unit8-win-stack',
  title: 'SafeSEH / SEHOP',
  desc: '<b>Goal:</b> Learn about SEH mitigations. <b>SafeSEH:</b> Compiler generates a table of valid handler addresses — runtime checks handler is in the table before calling it. Bypass: use a module compiled <i>without</i> SafeSEH. <b>SEHOP:</b> OS validates the entire SEH chain is intact before dispatching — checks that the chain ends at <code>ntdll!FinalExceptionHandler</code>.',
  source: {
    c: [
      { text: '// SafeSEH (Compile-time)', cls: 'comment' },
      { text: '// Compiler creates table of valid handlers', cls: 'comment' },
      { text: '// Runtime: is handler in the table? If not, crash', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// SafeSEH Bypass strategies:', cls: 'comment' },
      { text: '// 1. Find module without SafeSEH (common!)', cls: 'comment' },
      { text: '//    - Old DLLs, third-party libraries', cls: 'comment' },
      { text: '// 2. Use heap addresses (not in any module)', cls: 'comment' },
      { text: '// 3. Point handler to non-SafeSEH module', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// SEHOP (OS-level, Vista SP1+)', cls: 'comment' },
      { text: '// Validates SEH chain integrity:', cls: 'comment' },
      { text: '// 1. Walk the chain from fs:[0]', cls: 'comment' },
      { text: '// 2. Must end at ntdll!FinalExceptionHandler', cls: 'comment' },
      { text: '// 3. If chain is corrupt → access violation', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// SEHOP Bypass:', cls: 'comment' },
      { text: '// Reconstruct valid chain ending:', cls: 'comment' },
      { text: '// [nSEH] → [handler] → ... → [FinalHandler]', cls: 'comment' },
      { text: '// Need to know ntdll address (leak it first)', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0xb8], mnemonic: 'mov', operands: 'eax, 0x77123456', comment: 'Valid handler addr (in SafeSEH table)' },
    { addr: 0x00401005, bytes: [0xbb], mnemonic: 'mov', operands: 'ebx, 0x10001234', comment: 'Bypass: handler in non-SafeSEH module!' },
    { addr: 0x0040100a, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 0x7c9032bc', comment: 'SEHOP: ntdll!FinalExceptionHandler addr' },
    { addr: 0x0040100f, bytes: [0xba], mnemonic: 'mov', operands: 'edx, 0xffffffff', comment: 'End-of-chain marker (prev = -1)' },
    { addr: 0x00401014, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'SafeSEH + SEHOP understood!' },
  ],
  check: () => true,
  winTitle: 'SEH Mitigations!',
  winMsg: 'You understand SafeSEH and SEHOP — and their bypass strategies.',
};
