import { Exercise } from '../types';

export const win42: Exercise = {
  id: 'win-42',
  unitId: 'unit8-win-stack',
  title: 'Control Flow Guard',
  desc: '<b>Goal:</b> CFG (Control Flow Guard) is Microsoft\'s forward-edge CFI (Control Flow Integrity). Before every indirect call, the compiler inserts a check: <code>__guard_check_icall</code> verifies the target is a valid function entry point. This stops ROP/JOP that targets the middle of functions. Bypass requires a valid function address or CFG bitmap corruption.',
  source: {
    c: [
      { text: '// CFG — Control Flow Guard (Win 8.1+)', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// What it protects:', cls: 'comment' },
      { text: '// Indirect calls (function pointers, vtables)', cls: 'comment' },
      { text: '// call [eax] → first validates eax target', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// How it works:', cls: 'comment' },
      { text: '// 1. Compiler builds bitmap of valid call targets', cls: 'comment' },
      { text: '// 2. Before indirect call:', cls: 'comment' },
      { text: '//    mov ecx, target_addr', cls: 'comment' },
      { text: '//    call __guard_check_icall', cls: 'comment' },
      { text: '//    call ecx  ; only if check passed', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// CFG bitmap:', cls: 'comment' },
      { text: '// Each bit = 8-byte aligned address', cls: 'comment' },
      { text: '// 1 = valid call target, 0 = invalid', cls: 'comment' },
      { text: '', cls: '' },
      { text: '// Bypass strategies:', cls: 'comment' },
      { text: '// 1. Target a valid function (still in bitmap)', cls: 'comment' },
      { text: '// 2. Corrupt the CFG bitmap itself', cls: 'comment' },
      { text: '// 3. Use backward-edge (RET) — CFG is forward-only', cls: 'comment' },
      { text: '// 4. Find JIT pages (often not protected)', cls: 'comment' },
    ],
  },
  mode: 'asm-step',
  vizMode: 'asm',
  asmInstructions: [
    { addr: 0x00401000, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 0x00401500', comment: 'Target function address' },
    { addr: 0x00401005, bytes: [0xe8], mnemonic: 'call', operands: '0x00401100', comment: '__guard_check_icall(ecx) — validates target' },
    { addr: 0x0040100a, bytes: [0xff, 0xd1], mnemonic: 'call', operands: 'ecx', comment: 'Indirect call — only reached if CFG passed' },
    { addr: 0x0040100c, bytes: [0xb9], mnemonic: 'mov', operands: 'ecx, 0x00401337', comment: 'Attacker target (middle of function)' },
    { addr: 0x00401011, bytes: [0xe8], mnemonic: 'call', operands: '0x00401100', comment: '__guard_check_icall — FAILS! Not in bitmap' },
    { addr: 0x00401016, bytes: [0xf4], mnemonic: 'hlt', operands: '', comment: 'CFG blocks invalid call targets' },
    // Fake check function
    { addr: 0x00401100, bytes: [0xc3], mnemonic: 'ret', operands: '', comment: '(simplified check — real one reads CFG bitmap)' },
  ],
  check: () => true,
  winTitle: 'CFG Understood!',
  winMsg: 'You understand Control Flow Guard — forward-edge protection against indirect call hijacking.',
};
